# Generated by Django 3.0.6 on 2020-05-16 09:48

from django.db import migrations, models
import shop_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, validators=[shop_app.models.validate_name])),
                ('price', models.IntegerField(validators=[shop_app.models.validate_price])),
                ('user', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['user'],
            },
        ),
    ]
